// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'main.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 9047290881281150654),
      name: 'LocationPoint',
      lastPropertyId: const IdUid(3, 1099005163794573876),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6187179760719801029),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1666612252405032597),
            name: 'lat',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 1099005163794573876),
            name: 'lang',
            type: 8,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 9047290881281150654),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    LocationPoint: EntityDefinition<LocationPoint>(
        model: _entities[0],
        toOneRelations: (LocationPoint object) => [],
        toManyRelations: (LocationPoint object) => {},
        getId: (LocationPoint object) => object.id,
        setId: (LocationPoint object, int id) {
          object.id = id;
        },
        objectToFB: (LocationPoint object, fb.Builder fbb) {
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addFloat64(1, object.lat);
          fbb.addFloat64(2, object.lang);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = LocationPoint(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              lat: const fb.Float64Reader().vTableGet(buffer, rootOffset, 6, 0),
              lang:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [LocationPoint] entity fields to define ObjectBox queries.
class LocationPoint_ {
  /// see [LocationPoint.id]
  static final id =
      QueryIntegerProperty<LocationPoint>(_entities[0].properties[0]);

  /// see [LocationPoint.lat]
  static final lat =
      QueryDoubleProperty<LocationPoint>(_entities[0].properties[1]);

  /// see [LocationPoint.lang]
  static final lang =
      QueryDoubleProperty<LocationPoint>(_entities[0].properties[2]);
}
